apiVersion: v1
kind: Service
metadata:
  name: real-estate-service
spec:
  # This is the Azure magic:
  # AKS will automatically create a public Azure Load Balancer
  # with a real, public IP address for this service.
  type: LoadBalancer 
  
  selector:
    app: real-estate-site # This must match the 'app' label in your deployment.yaml
    
  ports:
  - protocol: TCP
    port: 80       # The Load Balancer's port (public)
    targetPort: 80 # The port on your Nginx pod (internal)